### ISSUE TITLE
ValueError: Program neato not found in path.

### ISSUE THREAD

**Issue by vinven7** [diogo-p-nunes/graph-representation#1]
When I run this notebook as it is, I get a message saying

`
ValueError: Program neato not found in path.
`

**Comment by vinven7** [comment]
`
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/vineeth/lib/python3.6/site-packages/pygraphviz/agraph.py in _get_prog(self, prog)
   1295         try:  # user must pick one of the graphviz programs...
-> 1296             runprog = self._which(prog)
   1297         except:

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/pygraphviz/agraph.py in _which(self, name)
   1529                 return match[0]
-> 1530         raise ValueError("No prog %s in path." % name)
   1531 

ValueError: No prog neato in path.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-10-3d271a204e2a> in <module>
      1 G = build_graph(doc)
----> 2 plot_graph(G, title='1) Undirected, unweighted graph')

<ipython-input-9-287c83e8e288> in plot_graph(G, title)
      4 
      5     # define position of nodes in figure
----> 6     pos = nx.nx_agraph.graphviz_layout(G)
      7 
      8     # draw nodes and edges

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/networkx/drawing/nx_agraph.py in graphviz_layout(G, prog, root, args)
    235     This is a wrapper for pygraphviz_layout.
    236     """
--> 237     return pygraphviz_layout(G, prog=prog, root=root, args=args)
    238 
    239 

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/networkx/drawing/nx_agraph.py in pygraphviz_layout(G, prog, root, args)
    283         args += f"-Groot={root}"
    284     A = to_agraph(G)
--> 285     A.layout(prog=prog, args=args)
    286     node_pos = {}
    287     for n in G:

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/pygraphviz/agraph.py in layout(self, prog, args)
   1358         """
   1359         fmt = 'dot'
-> 1360         data = self._run_prog(prog, ' '.join([args, "-T", fmt]))
   1361         self.from_string(data)
   1362         self.has_layout = True

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/pygraphviz/agraph.py in _run_prog(self, prog, args)
   1309         Use keyword args to add additional arguments to graphviz programs.
   1310         """
-> 1311         runprog = r'"%s"' % self._get_prog(prog)
   1312         cmd = ' '.join([runprog, args])
   1313         dotargs = shlex.split(cmd)

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/pygraphviz/agraph.py in _get_prog(self, prog)
   1296             runprog = self._which(prog)
   1297         except:
-> 1298             raise ValueError("Program %s not found in path." % prog)
   1299 
   1300         return runprog

ValueError: Program neato not found in path.

<Figure size 720x720 with 0 Axes>
`

**Comment by vinven7** [comment]
I followed some stackoverflow comments and manually inserted it into the path:

`
if  not 'C:\\Program Files (x86)\\Graphviz2.38\\bin' in os.environ["PATH"]: 
    os.environ["PATH"] += os.pathsep + 'C:\\Program Files (x86)\\Graphviz2.38\\bin' 
`

but still getting the same error

**Comment by vinven7** [comment]
The problem seems to be with the pos. I was able to make it work with     

`pos = nx.kamada_kawai_layout(G)`

**Comment by diogo-p-nunes** [comment]
Hello. You are most likely having problems with graphviz on your machine. By changing to another layout, you can skip graphviz altogether.
